version: '3.5'
services:

  postgres_db:
    container_name: pg_db
    image: postgres
    environment:   # Set up postgres database name and password
      POSTGRES_PASSWORD: password
      POSTGRES_DB: freetomove
      POSTGRES_USER: master
    ports:    # Set up ports exposed for other containers to connect to
      - 5433:5432
    networks:
      - app-tier

  python_app:
    container_name: python_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
    volumes:
      - $PWD/data:/home/data
      - $PWD/src:/src
    networks:
      - app-tier
    command:
      tail -f /dev/null


networks:
  app-tier:
    driver: bridge